name: CI for mobile devices
on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    strategy:
      matrix:
        preset: [android-arm64, android-x86_64, ios, ios_sim]
        version: [3.1.0, 3.0.8, 1.1.1t]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.cpm
            ${{ github.workspace }}/.ccache
          key: openssl-${{ matrix.version }}-${{ matrix.preset }}-${{ github.run_id }}
          restore-keys: openssl-${{ matrix.version }}-${{ matrix.preset }}

      - name: Install dependencies
        run: |
          brew update
          brew install ccache ninja

      - name: Set ccache path
        run: ccache -o cache_dir=${{ github.workspace }}/.ccache
      - name: Reset ccache statistics
        run: ccache -z

      - name: Configure
        run: cmake --preset ${{ matrix.preset }} -DCPM_SOURCE_CACHE="${{ github.workspace }}/.cpm" -DOPENSSL_TARGET_VERSION="${{ matrix.version }}"

      - name: Build
        run: cmake --build --preset ${{ matrix.preset }}

      - name: Install
        run: cmake --build --preset ${{ matrix.preset }}-install

      - name: Show ccache statistics
        run: ccache -sv
