name: CI for mobile devices
on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    strategy:
      matrix:
        preset: [android-arm64, android-x86_64, ios, ios_sim]
        version: [3.1.0, 3.0.8, 1.1.1t]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: .cpm
          key: openssl-cpm-${{ matrix.version }}
          enableCrossOsArchive: true
      - uses: actions/cache@v3
        with:
          path: .ccache
          key: openssl-ccache-${{ matrix.version }}-${{ matrix.preset }}-${{ github.run_id }}
          restore-keys: openssl-ccache-${{ matrix.version }}-${{ matrix.preset }}-

      - name: Install dependencies
        run: |
          brew update
          brew install ccache ninja

      - name: Configure ccache
        run: |
          ccache -o cache_dir=${{ github.workspace }}/.ccache
          ccache -z

      - name: Configure
        run: cmake --preset ${{ matrix.preset }} -DCPM_SOURCE_CACHE=".cpm" -DOPENSSL_TARGET_VERSION="${{ matrix.version }}"

      - name: Build
        run: cmake --build --preset ${{ matrix.preset }}

      - name: Install
        run: cmake --build --preset ${{ matrix.preset }}-install

      - name: Show ccache statistics
        run: ccache -sv
