name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version: [1.1.1u, 3.0.9, 3.1.1]
        preset:
          - android-arm
          - android-arm64
          - android-x86
          - android-x86_64
          - ios
          - ios_sim
          - linux-x86_64
          - macos-x86_64
          - windows-x86_64
        include:
          - preset: android-arm
            os: ubuntu-latest
          - preset: android-arm64
            os: ubuntu-latest
          - preset: android-x86
            os: ubuntu-latest
          - preset: android-x86_64
            os: ubuntu-latest
          - preset: ios
            os: macos-latest
          - preset: ios_sim
            os: macos-latest
          - preset: linux-x86_64
            os: ubuntu-latest
          - preset: macos-x86_64
            os: macos-latest
          - preset: windows-x86_64
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: .cpm
          key: openssl-${{ matrix.version }}-cpm
          enableCrossOsArchive: true
      - uses: actions/cache@v3
        with:
          path: .ccache
          key: openssl-${{ matrix.version }}-ccache-${{ matrix.preset }}-${{ github.run_id }}
          restore-keys: openssl-${{ matrix.version }}-ccache-${{ matrix.preset }}-

      - name: Install dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build ccache
      - name: Install dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install ccache
      - name: Install dependencies on Windows
        if: runner.os == 'Windows'
        run: |
          choco install -y jom nasm ccache
          echo "PATH=$ENV:PATH;C:\Program Files\NASM" >> $ENV:GITHUB_ENV

      - name: Configure ccache
        run: |
          ccache -o cache_dir=${{ github.workspace }}/.ccache
          ccache -z

      - name: Configure CMake
        run: >
          cmake --preset ${{ matrix.preset }}
          -DCPM_SOURCE_CACHE=".cpm"
          -DOPENSSL_BUILD_VERBOSE=ON
          -DOPENSSL_CONFIGURE_VERBOSE=ON
          -DOPENSSL_CONFIGURE_OPTIONS="--prefix=${{ github.workspace }}/install"
          -DOPENSSL_TARGET_VERSION="${{ matrix.version }}"

      - name: Build
        run: cmake --build --preset ${{ matrix.preset }} --config Release

      - name: Test
        if: contains(fromJSON('["linux-x86_64", "macos-x86_64", "windows-x86_64"]'), matrix.preset)
        run: ctest --preset ${{ matrix.preset }} -C Release

      - name: Install
        run: cmake --build --preset ${{ matrix.preset }}-install --config Release

      - name: Show ccache statistics
        run: ccache -sv
