name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        preset: [android, ios, linux, macos, windows]
        version: [1.1.1u, 3.0.9, 3.1.1]
        include:
          - { os: macos, preset: ios }
          - { os: macos, preset: macos }
          - { os: ubuntu, preset: android }
          - { os: ubuntu, preset: linux }
          - { os: windows, preset: windows }
    name: ${{ matrix.preset }}-${{ matrix.version }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: .cpm
          key: openssl-${{ matrix.version }}-cpm
          enableCrossOsArchive: true
      - uses: actions/cache@v3
        with:
          path: .ccache
          key: openssl-${{ matrix.version }}-ccache-${{ matrix.preset }}-${{ github.run_id }}
          restore-keys: openssl-${{ matrix.version }}-ccache-${{ matrix.preset }}-

      - name: Install dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build ccache
      - name: Install dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install ccache
      - name: Install dependencies on Windows
        if: runner.os == 'Windows'
        run: |
          choco install -y jom nasm ccache
          echo "PATH=$ENV:PATH;C:\Program Files\NASM" >> $ENV:GITHUB_ENV

      - name: Configure ccache
        run: |
          ccache -o cache_dir=${{ github.workspace }}/.ccache
          ccache -z

      - name: Configure CMake
        run: >
          cmake --preset ${{ matrix.preset }}
          -DCPM_SOURCE_CACHE=".cpm"
          -DOPENSSL_BUILD_VERBOSE=ON
          -DOPENSSL_CONFIGURE_VERBOSE=ON
          -DOPENSSL_TARGET_VERSION="${{ matrix.version }}"

      - name: Build
        run: cmake --build --preset ${{ matrix.preset }}

      - name: Test
        if: contains(fromJSON('["linux", "macos", "windows"]'), matrix.preset)
        run: ctest --preset ${{ matrix.preset }}

      - name: Show ccache statistics
        run: ccache -sv
