name: CI
on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [3.1.0, 3.0.8, 1.1.1t]
        include:
          - os: ubuntu-latest
            preset: linux-x86_64
          - os: macos-latest
            preset: macos-x86_64
          - os: windows-latest
            preset: windows-x64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.cpm
            ${{ github.workspace }}/.ccache
          key: openssl-${{ matrix.version }}-${{ matrix.preset }}-${{ github.run_id }}
          restore-keys: openssl-${{ matrix.version }}-${{ matrix.preset }}

      - name: Install dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build ccache
      - name: Install dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install ccache
      - name: Install dependencies on Windows
        if: runner.os == 'Windows'
        run: |
          choco install -y jom nasm ccache
          echo "PATH=$ENV:PATH;C:\Program Files\NASM" >> $ENV:GITHUB_ENV

      - name: Set ccache path
        run: ccache -o cache_dir=${{ github.workspace }}/.ccache
      - name: Reset ccache statistics
        run: ccache -z

      - name: Configure
        run: cmake --preset ${{ matrix.preset }} -DCPM_SOURCE_CACHE="${{ github.workspace }}/.cpm" -DOPENSSL_TARGET_VERSION="${{ matrix.version }}"

      - name: Build
        run: cmake --build --preset ${{ matrix.preset }}

      - name: Test
        run: ctest --preset ${{ matrix.preset }}

      - name: Install
        run: cmake --build --preset ${{ matrix.preset }}-install

      - name: Show ccache statistics
        run: ccache -sv
